version: '3.1'

services:
  register.jar:
    container_name: register.jar
    image: register.jar
    restart: always
    build: ./
    ports:
      - "1111:1111"
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5555/techcareerairtiesgateway
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
  postgresqldb:
    image: postgres
    container_name: postgresqldb
    restart: always
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=techcareerairtiesgateway