version: '3.1'
services:
  app:
    container_name: micro.jar
    image: micro.jar
    restart: always
    build: ..
    ports:
      - "1111:1111"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=techcareerairtiesgateway