version: '3'

services:
  registerloginapp:
    container_name: register.jar
    restart: always
    build: ./
    ports:
      - "1111:1111"
    networks:
      - daily_default
networks:
  daily_default:
    name: daily_default
    driver: bridge